version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: inventory_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: inventory_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - inventory_network

  # Backend API
  backend:
    image: arjun1303/inventory-backend:latest
    container_name: inventory_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGO_URI=mongodb://mongodb:27017/inventory_db
      - JWT_SECRET=your_super_secret_jwt_key_change_this_in_production
    depends_on:
      - mongodb
    networks:
      - inventory_network

  # Frontend React App
  frontend:
    image: arjun1303/inventory-frontend:latest
    container_name: inventory_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - inventory_network

# Named volumes for data persistence
volumes:
  mongodb_data:

# Networks for container communication
networks:
  inventory_network:
    driver: bridge
